apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
    name: "heapster"
  name: "monitoring-heapster-controller"
spec:
  replicas: 1
  selector:
    name: "heapster"
  template:
    metadata:
      labels:
        name: "heapster"
    spec:
      serviceAccount: "heapster"
      containers:
        -
          image: "kubernetes/heapster"
          name: "heapster"
          command:
            - "/heapster"
            - "--source=kubernetes:http://127.0.0.1:8080?inClusterConfig=false&useServiceAccount=true&auth="
            - "--sink=influxdb:http://172.17.0.7:8086"
