apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb
  namespace: thoth
  labels:
    name: influxdb
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      containers:
      - name: influxdb
        image: tutum/influxdb:0.10
        ports:
        - name: webui
          containerPort: 8083
        - name: api
          containerPort: 8086
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data 
          hostPath: 
            path: /var/lib/influxdb
